import "./globals.css";
import Topo from "@/app/componentes/Topo";
import Rodape from "@/app/componentes/Rodape";

export const metadata = {
  title: "Sorveteria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Topo />
        {children}
        <Rodape />
      </body>
    </html>
  );
}
